apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysqlpv01
  annotations:
    volume.beta.kubernetes.io/storage-class: "slow"
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.1.230
    path: /nfs/mysql01
