apiVersion: v1
kind: Pod
metadata:
  name: mysql01
  labels:
    app: mysql
spec:
  volumes:
    - name: "mysql-persistent-storage"
      persistentVolumeClaim:
        claimName: mysql-pv-claim
  containers:
  - name: mysql
    image: mysql
    ports:
    - containerPort: 3306
    volumeMounts:
    - mountPath: /var/lib/mysql/
      name: mysql-persistent-storage

