# based on...
# https://qiita.com/hhiroshell/items/5e81cac3e9c059029837
apiVersion: v1
kind: Service
metadata:
  name: mysql01
spec:
  ports:
  - port: 3306
  selector:
    app: mysql01
  clusterIP: None
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1beta1 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: mysql-server
spec:
  selector:
    matchLabels:
      app: mysql-server
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql-server
    spec:
      containers:
      - image: mysql/mysql:8.0.19
        name: mysql-server
        env:
        - name: MYSQL_ROOT_PASSWORD
          # value: user defined into file.
          valueFrom:
            secretKeyRef:
              name: db-user-pass
              key: root_password
        - name: MYSQL_USER
          # value: user defined into file.
          valueFrom:
            secretKeyRef:
              name: db-user-pass
              key: username
        - name: MYSQL_PASSWORD
          # value: user defined into file.
          valueFrom:
            secretKeyRef:
              name: db-user-pass
              key: password
        - name: MYSQL_DATABASE
          value: "app"
        ports:
        - containerPort: 3306
          name: mysql-server
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim
