apiVersion: v1
kind: Service
metadata:
  name: payara-externalip
spec:
  type: ClusterIP
  externalIPs:
    - 192.168.1.211
    - 192.168.1.212
    - 192.168.1.213
    - 192.168.1.214
  ports:
    - name: "payara-admin"
      protocol: "TCP"
      port: 4848
      targetPort: 4848
  selector:
    app: payara-app
