apiVersion: v1
kind: Service
metadata:
  name: sample-externalip
spec:
  type: ClusterIP
  externalIPs:
    - 192.168.1.211
    - 192.168.1.212
    - 192.168.1.213
    - 192.168.1.214
  ports:
    - name: "http-port"
      protocol: "TCP"
      port: 8080
      targetPort: 8080
    - name: "https-port"
      protocol: "TCP"
      port: 8181
      targetPort: 8181
    - name: "admin-port"
      protocol: "TCP"
      port: 4848
      targetPort: 4848
    - name: "debug-port"
      protocol: "TCP"
      port: 9009
      targetPort: 9009
  selector:
    app: payara-app
