apiVersion: v1
kind: Pod
metadata:
  name: httpd
  labels:
    app: httpd
spec:
  volumes:
    - name: "httpd-persistent-storage"
      persistentVolumeClaim:
        claimName: httpd-pv-claim
  containers:
  - name: httpd
    image: httpd
    ports:
    - containerPort: 80
    volumeMounts:
    - mountPath: /usr/local/apache2/htdocs/
      name: httpd-persistent-storage

